project:
  type: website
  output-dir: docs

website:
  title: "Renee's Blog"
  site-url: https://reneegf.github.io/my_blog/
  navbar:
    right:
      - about.qmd
      - index.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: litera
    css: styles.css



